/*
 * This file was generated by the Gradle "init" task.
 *
 * The settings file is used to specify which projects to include in your build.
 * 
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/4.6/userguide/multi_project_builds.html
 */

rootProject.name = "OrchidTutorials"

include("01")
include("02")
include("03")
include("04")
include("05")
include("06")
include("07")

include(":groovy-site:app")
include(":groovy-site:docs")

include(":java-site:app")
include(":java-site:docs")

include(":kotlin-site:app")
include(":kotlin-site:docs")

include(":swift-site:app")
include(":swift-site:docs")

include(":combined-docs-site")

include(":kotlin-mpp-site:app")
include(":kotlin-mpp-site:docs")

include(":blog-site")
